# Generated by Django 4.0.3 on 2024-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expid', models.IntegerField()),
                ('expense_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(blank=True, choices=[('CASH', 'cash'), ('CHEQUE', 'cheque'), ('DEMAND DRAFT', 'demand draft'), ('Transfer', 'transfer')], max_length=15, null=True)),
                ('reason', models.TextField(blank=True, max_length=300, null=True)),
                ('expense_by', models.CharField(blank=True, max_length=100, null=True)),
                ('bankname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('chequeordd', models.IntegerField(blank=True, default=None, null=True)),
                ('dateinbank', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('details', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etypeid', models.IntegerField()),
                ('etypename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incid', models.IntegerField()),
                ('income_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(blank=True, choices=[('CASH', 'cash'), ('CHEQUE', 'cheque'), ('DEMAND DRAFT', 'demand draft'), ('Transfer', 'transfer')], max_length=15, null=True)),
                ('reason', models.TextField(blank=True, max_length=300, null=True)),
                ('income_by', models.CharField(blank=True, max_length=100, null=True)),
                ('bankname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('chequeordd', models.IntegerField(blank=True, null=True)),
                ('dateinbank', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('details', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField()),
                ('typename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashinhand', models.IntegerField(blank=True, null=True)),
                ('cashatbank', models.IntegerField(blank=True, null=True)),
                ('cashatbankexp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
